version: "1"
networks:
  downstairs:
    driver: bridge
services:
  nginx:
    depends_on:
      - app
    networks:
      - downstairs
    ports:
      - "80:80"
    volumes:
      - app-logs:/var/www/html/share/logs/app
      - scheduler-logs:/var/www/html/share/logs/scheduler
      - queue-worker-logs:/var/www/html/share/logs/queue-worker
    image: registryproductiondownstairs.azurecr.io/laravel/nginx:1.30.0
  app:
    environment:
      - APP_TYPE=app
    networks:
      - downstairs
    ports:
      - "9000"
    volumes:
      - app-logs:/var/www/html/storage/logs
    image: registryproductiondownstairs.azurecr.io/laravel/php-fpm:1.30.0
  scheduler:
    networks:
      - downstairs
    volumes:
      - scheduler-logs:/var/www/html/storage/logs
      - app-logs:/var/www/html/storage/share/logs/app
      - queue-worker-logs:/var/www/html/storage/share/logs/queue-worker
    command: crond -f -L /dev/null
    image: registryproductiondownstairs.azurecr.io/laravel/php-fpm:1.30.0
  queue-worker:
    environment:
      - APP_TYPE=queue-worker
    networks:
      - downstairs
    volumes:
      - queue-worker-logs:/var/www/html/storage/logs
    image: registryproductiondownstairs.azurecr.io/laravel/php-fpm:1.30.0
    restart: always
volumes:
  app-logs:
  scheduler-logs:
  queue-worker-logs:
