<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        if (app()->environment() === 'testing') {
            Country::create([
                'id' => 217,
                'name' => 'Sweden',
                'code' => 'SE',
                'currency' => 'SEK',
                'dial_code' => '46',
                'flag' => '🇸🇪',
            ]);
        } else {
            $result = [];

            foreach ($this->getCountries() as $item) {
                $parts = explode('_', $item);

                $result[] = [
                    'name' => $parts[0],
                    'code' => $parts[1],
                    'currency' => $parts[2],
                    'dial_code' => $parts[3],
                    'flag' => $parts[4],
                ];
            }

            Country::insert($result);
        }
    }

    private function getCountries(): array
    {
        return [
            'Afghanistan_AF_AFN_93_🇦🇫',
            'Åland_AX_EUR_358_🇦🇽',
            'Albania_AL_ALL_355_🇦🇱',
            'Algeria_DZ_DZD_213_🇩🇿',
            'American Samoa_AS_USD_1684_🇦🇸',
            'Andorra_AD_EUR_376_🇦🇩',
            'Angola_AO_AOA_244_🇦🇴',
            'Anguilla_AI_XCD_1264_🇦🇮',
            'Antarctica_AQ_ARS_672_🇦🇶',
            'Antigua and Barbuda_AG_XCD_1268_🇦🇬',
            'Argentina_AR_ARS_54_🇦🇷',
            'Armenia_AM_AMD_374_🇦🇲',
            'Aruba_AW_AWG_297_🇦🇼',
            'Australia_AU_AUD_61_🇦🇺',
            'Austria_AT_EUR_43_🇦🇹',
            'Azerbaijan_AZ_AZN_994_🇦🇿',
            'Bahamas_BS_BSD_1242_🇧🇸',
            'Bahrain_BH_BHD_973_🇧🇭',
            'Bangladesh_BD_BDT_880_🇧🇩',
            'Barbados_BB_BBD_1246_🇧🇧',
            'Belarus_BY_BYN_375_🇧🇾',
            'Belgium_BE_EUR_32_🇧🇪',
            'Belize_BZ_BZD_501_🇧🇿',
            'Benin_BJ_XOF_229_🇧🇯',
            'Bermuda_BM_BMD_1441_🇧🇲',
            'Bhutan_BT_BTN_975_🇧🇹',
            'Bolivia_BO_BOB_591_🇧🇴',
            'Bonaire_BQ_USD_599_🇧🇶',
            'Bosnia and Herzegovina_BA_BAM_387_🇧🇦',
            'Botswana_BW_BWP_267_🇧🇼',
            'Bouvet Island_BV_NOK_47_🇧🇻',
            'Brazil_BR_BRL_55_🇧🇷',
            'British Indian Ocean Territory_IO_USD_246_🇮🇴',
            'British Virgin Islands_VG_USD_1284_🇻🇬',
            'Brunei_BN_BND_673_🇧🇳',
            'Bulgaria_BG_BGN_359_🇧🇬',
            'Burkina Faso_BF_XOF_226_🇧🇫',
            'Burundi_BI_BIF_257_🇧🇮',
            'Cambodia_KH_KHR_855_🇰🇭',
            'Cameroon_CM_XAF_237_🇨🇲',
            'Canada_CA_CAD_1_🇨🇦',
            'Cape Verde_CV_CVE_238_🇨🇻',
            'Cayman Islands_KY_KYD_1345_🇰🇾',
            'Central African Republic_CF_XAF_236_🇨🇫',
            'Chad_TD_XAF_235_🇹🇩',
            'Chile_CL_CLP_56_🇨🇱',
            'China_CN_CNY_86_🇨🇳',
            'Christmas Island_CX_AUD_61_🇨🇽',
            'Cocos [Keeling] Islands_CC_AUD_61_🇨🇨',
            'Colombia_CO_COP_57_🇨🇴',
            'Comoros_KM_KMF_269_🇰🇲',
            'Cook Islands_CK_NZD_682_🇨🇰',
            'Costa Rica_CR_CRC_506_🇨🇷',
            'Croatia_HR_HRK_385_🇭🇷',
            'Cuba_CU_CUP_53_🇨🇺',
            'Curacao_CW_USD_599_🇨🇼',
            'Cyprus_CY_EUR_357_🇨🇾',
            'Czech Republic_CZ_CZK_420_🇨🇿',
            'Democratic Republic of the Congo_CD_CDF_243_🇨🇩',
            'Denmark_DK_DKK_45_🇩🇰',
            'Djibouti_DJ_DJF_253_🇩🇯',
            'Dominica_DM_XCD_1767_🇩🇲',
            'Dominican Republic_DO_DOP_1809_🇩🇴',
            'East Timor_TL_USD_670_🇹🇱',
            'Ecuador_EC_USD_593_🇪🇨',
            'Egypt_EG_EGP_20_🇪🇬',
            'El Salvador_SV_USD_503_🇸🇻',
            'Equatorial Guinea_GQ_XAF_240_🇬🇶',
            'Eritrea_ER_ERN_291_🇪🇷',
            'Estonia_EE_EUR_372_🇪🇪',
            'Ethiopia_ET_ETB_251_🇪🇹',
            'Falkland Islands_FK_FKP_500_🇫🇰',
            'Faroe Islands_FO_DKK_298_🇫🇴',
            'Fiji_FJ_FJD_679_🇫🇯',
            'Finland_FI_EUR_358_🇫🇮',
            'France_FR_EUR_33_🇫🇷',
            'French Guiana_GF_EUR_594_🇬🇫',
            'French Polynesia_PF_XPF_689_🇵🇫',
            'French Southern Territories_TF_EUR_262_🇹🇫',
            'Gabon_GA_XAF_241_🇬🇦',
            'Gambia_GM_GMD_220_🇬🇲',
            'Georgia_GE_GEL_995_🇬🇪',
            'Germany_DE_EUR_49_🇩🇪',
            'Ghana_GH_GHS_233_🇬🇭',
            'Gibraltar_GI_GIP_350_🇬🇮',
            'Greece_GR_EUR_30_🇬🇷',
            'Greenland_GL_DKK_299_🇬🇱',
            'Grenada_GD_XCD_1473_🇬🇩',
            'Guadeloupe_GP_EUR_590_🇬🇵',
            'Guam_GU_USD_1671_🇬🇺',
            'Guatemala_GT_GTQ_502_🇬🇹',
            'Guernsey_GG_GBP_44_🇬🇬',
            'Guinea_GN_GNF_224_🇬🇳',
            'Guinea-Bissau_GW_XOF_245_🇬🇼',
            'Guyana_GY_GYD_592_🇬🇾',
            'Haiti_HT_HTG_509_🇭🇹',
            'Heard Island and McDonald Islands_HM_AUD_672_🇭🇲',
            'Honduras_HN_HNL_504_🇭🇳',
            'Hong Kong_HK_HKD_852_🇭🇰',
            'Hungary_HU_HUF_36_🇭🇺',
            'Iceland_IS_ISK_354_🇮🇸',
            'India_IN_INR_91_🇮🇳',
            'Indonesia_ID_IDR_62_🇮🇩',
            'Iran_IR_IRR_98_🇮🇷',
            'Iraq_IQ_IQD_964_🇮🇶',
            'Ireland_IE_EUR_353_🇮🇪',
            'Isle of Man_IM_GBP_44_🇮🇲',
            'Israel_IL_ILS_972_🇮🇱',
            'Italy_IT_EUR_39_🇮🇹',
            'Ivory Coast_CI_XOF_225_🇨🇮',
            'Jamaica_JM_JMD_1876_🇯🇲',
            'Japan_JP_JPY_81_🇯🇵',
            'Jersey_JE_GBP_44_🇯🇪',
            'Jordan_JO_JOD_962_🇯🇴',
            'Kazakhstan_KZ_KZT_7_🇰🇿',
            'Kenya_KE_KES_254_🇰🇪',
            'Kiribati_KI_AUD_686_🇰🇮',
            'Kosovo_XK_EUR_383_🇽🇰',
            'Kuwait_KW_KWD_965_🇰🇼',
            'Kyrgyzstan_KG_KGS_996_🇰🇬',
            'Laos_LA_LAK_856_🇱🇦',
            'Latvia_LV_EUR_371_🇱🇻',
            'Lebanon_LB_LBP_961_🇱🇧',
            'Lesotho_LS_LSL_266_🇱🇸',
            'Liberia_LR_LRD_231_🇱🇷',
            'Libya_LY_LYD_218_🇱🇾',
            'Liechtenstein_LI_CHF_423_🇱🇮',
            'Lithuania_LT_EUR_370_🇱🇹',
            'Luxembourg_LU_EUR_352_🇱🇺',
            'Macao_MO_MOP_853_🇲🇴',
            'Macedonia_MK_MKD_389_🇲🇰',
            'Madagascar_MG_MGA_261_🇲🇬',
            'Malawi_MW_MWK_265_🇲🇼',
            'Malaysia_MY_MYR_60_🇲🇾',
            'Maldives_MV_MVR_960_🇲🇻',
            'Mali_ML_XOF_223_🇲🇱',
            'Malta_MT_EUR_356_🇲🇹',
            'Marshall Islands_MH_USD_692_🇲🇭',
            'Martinique_MQ_EUR_596_🇲🇶',
            'Mauritania_MR_MRO_222_🇲🇷',
            'Mauritius_MU_MUR_230_🇲🇺',
            'Mayotte_YT_EUR_262_🇾🇹',
            'Mexico_MX_MXN_52_🇲🇽',
            'Micronesia_FM_USD_691_🇫🇲',
            'Moldova_MD_MDL_373_🇲🇩',
            'Monaco_MC_EUR_377_🇲🇨',
            'Mongolia_MN_MNT_976_🇲🇳',
            'Montenegro_ME_EUR_382_🇲🇪',
            'Montserrat_MS_XCD_1664_🇲🇸',
            'Morocco_MA_MAD_212_🇲🇦',
            'Mozambique_MZ_MZN_258_🇲🇿',
            'Myanmar [Burma]_MM_MMK_95_🇲🇲',
            'Namibia_NA_NAD_264_🇳🇦',
            'Nauru_NR_AUD_674_🇳🇷',
            'Nepal_NP_NPR_977_🇳🇵',
            'Netherlands_NL_EUR_31_🇳🇱',
            'New Caledonia_NC_XPF_687_🇳🇨',
            'New Zealand_NZ_NZD_64_🇳🇿',
            'Nicaragua_NI_NIO_505_🇳🇮',
            'Niger_NE_XOF_227_🇳🇪',
            'Nigeria_NG_NGN_234_🇳🇬',
            'Niue_NU_NZD_683_🇳🇺',
            'Norfolk Island_NF_AUD_672_🇳🇫',
            'North Korea_KP_KPW_850_🇰🇵',
            'Northern Mariana Islands_MP_USD_1670_🇲🇵',
            'Norway_NO_NOK_47_🇳🇴',
            'Oman_OM_OMR_968_🇴🇲',
            'Pakistan_PK_PKR_92_🇵🇰',
            'Palau_PW_USD_680_🇵🇼',
            'Palestine_PS_ILS_970_🇵🇸',
            'Panama_PA_PAB_507_🇵🇦',
            'Papua New Guinea_PG_PGK_675_🇵🇬',
            'Paraguay_PY_PYG_595_🇵🇾',
            'Peru_PE_PEN_51_🇵🇪',
            'Philippines_PH_PHP_63_🇵🇭',
            'Pitcairn Islands_PN_NZD_64_🇵🇳',
            'Poland_PL_PLN_48_🇵🇱',
            'Portugal_PT_EUR_351_🇵🇹',
            'Puerto Rico_PR_USD_1787_🇵🇷',
            'Qatar_QA_QAR_974_🇶🇦',
            'Republic of the Congo_CG_XAF_242_🇨🇬',
            'Réunion_RE_EUR_262_🇷🇪',
            'Romania_RO_RON_40_🇷🇴',
            'Russia_RU_RUB_7_🇷🇺',
            'Rwanda_RW_RWF_250_🇷🇼',
            'Saint Barthélemy_BL_EUR_590_🇧🇱',
            'Saint Helena_SH_SHP_290_🇸🇭',
            'Saint Kitts and Nevis_KN_XCD_1869_🇰🇳',
            'Saint Lucia_LC_XCD_1758_🇱🇨',
            'Saint Martin_MF_EUR_590_🇲🇫',
            'Saint Pierre and Miquelon_PM_EUR_508_🇵🇲',
            'Saint Vincent and the Grenadines_VC_XCD_1784_🇻🇨',
            'Samoa_WS_WST_685_🇼🇸',
            'San Marino_SM_EUR_378_🇸🇲',
            'São Tomé and Príncipe_ST_STD_239_🇸🇹',
            'Saudi Arabia_SA_SAR_966_🇸🇦',
            'Senegal_SN_XOF_221_🇸🇳',
            'Serbia_RS_RSD_381_🇷🇸',
            'Seychelles_SC_SCR_248_🇸🇨',
            'Sierra Leone_SL_SLL_232_🇸🇱',
            'Singapore_SG_SGD_65_🇸🇬',
            'Sint Maarten_SX_ANG_1721_🇸🇽',
            'Slovakia_SK_EUR_421_🇸🇰',
            'Slovenia_SI_EUR_386_🇸🇮',
            'Solomon Islands_SB_SBD_677_🇸🇧',
            'Somalia_SO_SOS_252_🇸🇴',
            'South Africa_ZA_ZAR_27_🇿🇦',
            'South Georgia and the South Sandwich Islands_GS_GBP_500_🇬🇸',
            'South Korea_KR_KRW_82_🇰🇷',
            'South Sudan_SS_SSP_211_🇸🇸',
            'Spain_ES_EUR_34_🇪🇸',
            'Sri Lanka_LK_LKR_94_🇱🇰',
            'Sudan_SD_SDG_249_🇸🇩',
            'Suriname_SR_SRD_597_🇸🇷',
            'Svalbard and Jan Mayen_SJ_NOK_4779_🇸🇯',
            'Swaziland_SZ_SZL_268_🇸🇿',
            'Sweden_SE_SEK_46_🇸🇪',
            'Switzerland_CH_CHF_41_🇨🇭',
            'Syria_SY_SYP_963_🇸🇾',
            'Taiwan_TW_TWD_886_🇹🇼',
            'Tajikistan_TJ_TJS_992_🇹🇯',
            'Tanzania_TZ_TZS_255_🇹🇿',
            'Thailand_TH_THB_66_🇹🇭',
            'Togo_TG_XOF_228_🇹🇬',
            'Tokelau_TK_NZD_690_🇹🇰',
            'Tonga_TO_TOP_676_🇹🇴',
            'Trinidad and Tobago_TT_TTD_1868_🇹🇹',
            'Tunisia_TN_TND_216_🇹🇳',
            'Turkey_TR_TRY_90_🇹🇷',
            'Turkmenistan_TM_TMT_993_🇹🇲',
            'Turks and Caicos Islands_TC_USD_1649_🇹🇨',
            'Tuvalu_TV_AUD_688_🇹🇻',
            'U.S. Minor Outlying Islands_UM_USD_1_🇺🇲',
            'U.S. Virgin Islands_VI_USD_1340_🇻🇮',
            'Uganda_UG_UGX_256_🇺🇬',
            'Ukraine_UA_UAH_380_🇺🇦',
            'United Arab Emirates_AE_AED_971_🇦🇪',
            'United Kingdom_GB_GBP_44_🇬🇧',
            'United States_US_USD_1_🇺🇸',
            'Uruguay_UY_UYU_598_🇺🇾',
            'Uzbekistan_UZ_UZS_998_🇺🇿',
            'Vanuatu_VU_VUV_678_🇻🇺',
            'Vatican City_VA_EUR_39_🇻🇦',
            'Venezuela_VE_VEF_58_🇻🇪',
            'Vietnam_VN_VND_84_🇻🇳',
            'Wallis and Futuna_WF_XPF_681_🇼🇫',
            'Western Sahara_EH_MAD_212_🇪🇭',
            'Yemen_YE_YER_967_🇾🇪',
            'Zambia_ZM_ZMW_260_🇿🇲',
            'Zimbabwe_ZW_ZWL_263_🇿🇼',
        ];
    }
}
