parameters:
  - name: phpVersion
    type: string

steps:
  - bash: |
      sudo update-alternatives --set php /usr/bin/php${PHP_VERSION}
      sudo update-alternatives --set phar /usr/bin/phar${PHP_VERSION}
      sudo update-alternatives --set phpdbg /usr/bin/phpdbg${PHP_VERSION}
      sudo update-alternatives --set php-cgi /usr/bin/php-cgi${PHP_VERSION}
      sudo update-alternatives --set phar.phar /usr/bin/phar.phar${PHP_VERSION}
      php -version
    env:
      PHP_VERSION: ${{ parameters.phpVersion }}
    displayName: Set PHP version to ${{ parameters.phpVersion }}

  - bash: |
      sudo add-apt-repository ppa:ondrej/php
      sudo apt update
      sudo apt install -y \
        php${PHP_VERSION}-cli php${PHP_VERSION}-common \
        php${PHP_VERSION}-mysql php${PHP_VERSION}-zip \
        php${PHP_VERSION}-gd php${PHP_VERSION}-mbstring \
        php${PHP_VERSION}-curl php${PHP_VERSION}-xml \
        php${PHP_VERSION}-bcmath php${PHP_VERSION}-fpm \
        php${PHP_VERSION}-intl php${PHP_VERSION}-redis \
        php${PHP_VERSION}-sqlite3 composer
    env:
      PHP_VERSION: ${{ parameters.phpVersion }}
    displayName: Install PHP extensions
