// THIS FILE IS AUTO-GENERATED. DO NOT EDIT THIS FILE MANUALLY.

const PERMISSIONS = {
  "access portal": {
    value: "access portal",
    label: "portal access",
    group: "access",
  },
  "access cashier": {
    value: "access cashier",
    label: "cashier access",
    group: "access",
  },
  "access customer app": {
    value: "access customer app",
    label: "customer app access",
    group: "access",
    requires: [
      "services index",
      "products index",
      "properties index",
      "properties create",
      "properties update",
      "properties delete",
      "schedules index",
      "schedules read",
      "schedules update",
      "schedules cancel",
      "schedule change requests create",
      "feedbacks create",
      "notifications index",
      "notifications read",
      "credits index",
    ],
  },
  "access employee app": {
    value: "access employee app",
    label: "employee app access",
    group: "access",
    requires: [
      "teams index",
      "teams read",
      "feedbacks create",
      "notifications index",
      "notifications read",
      "deviations create",
    ],
  },
  "customers index": {
    value: "customers index",
    label: "index",
    group: "customers",
  },
  "customers create": {
    value: "customers create",
    label: "create",
    group: "customers",
  },
  "customers read": {
    value: "customers read",
    label: "read",
    group: "customers",
  },
  "customers update": {
    value: "customers update",
    label: "update",
    group: "customers",
  },
  "customers delete": {
    value: "customers delete",
    label: "delete",
    group: "customers",
  },
  "customers restore": {
    value: "customers restore",
    label: "restore",
    group: "customers",
  },
  "customers wizard": {
    value: "customers wizard",
    label: "wizard",
    group: "customers",
  },
  "customers primary address read": {
    value: "customers primary address read",
    label: "read primary address",
    group: "customers",
  },
  "customers primary address update": {
    value: "customers primary address update",
    label: "update primary address",
    group: "customers",
  },
  "customer invoice addresses index": {
    value: "customer invoice addresses index",
    label: "invoice address index",
    group: "customers",
  },
  "customer invoice addresses create": {
    value: "customer invoice addresses create",
    label: "create invoice address",
    group: "customers",
  },
  "customer invoice addresses update": {
    value: "customer invoice addresses update",
    label: "update invoice address",
    group: "customers",
  },
  "customer schedules index": {
    value: "customer schedules index",
    label: "schedule index",
    group: "customers",
  },
  "customer schedule histories index": {
    value: "customer schedule histories index",
    label: "schedule history index",
    group: "customers",
  },
  "customer credits index": {
    value: "customer credits index",
    label: "credit index",
    group: "customers",
  },
  "customer invoice addresses delete": {
    value: "customer invoice addresses delete",
    label: "delete invoice address",
    group: "customers",
  },
  "customer invoice addresses restore": {
    value: "customer invoice addresses restore",
    label: "restore invoice address",
    group: "customers",
  },
  "fixed prices index": {
    value: "fixed prices index",
    label: "index",
    group: "fixed prices",
  },
  "fixed prices create": {
    value: "fixed prices create",
    label: "create",
    group: "fixed prices",
  },
  "fixed prices read": {
    value: "fixed prices read",
    label: "read",
    group: "fixed prices",
  },
  "fixed prices update": {
    value: "fixed prices update",
    label: "update",
    group: "fixed prices",
  },
  "fixed prices delete": {
    value: "fixed prices delete",
    label: "delete",
    group: "fixed prices",
  },
  "fixed prices restore": {
    value: "fixed prices restore",
    label: "restore",
    group: "fixed prices",
  },
  "fixed price rows index": {
    value: "fixed price rows index",
    label: "row index",
    group: "fixed prices",
  },
  "fixed price rows create": {
    value: "fixed price rows create",
    label: "create row",
    group: "fixed prices",
  },
  "fixed price rows update": {
    value: "fixed price rows update",
    label: "update row",
    group: "fixed prices",
  },
  "fixed price rows delete": {
    value: "fixed price rows delete",
    label: "delete row",
    group: "fixed prices",
  },
  "customer discounts index": {
    value: "customer discounts index",
    label: "index",
    group: "customer discounts",
  },
  "customer discounts create": {
    value: "customer discounts create",
    label: "create",
    group: "customer discounts",
  },
  "customer discounts read": {
    value: "customer discounts read",
    label: "read",
    group: "customer discounts",
  },
  "customer discounts update": {
    value: "customer discounts update",
    label: "update",
    group: "customer discounts",
  },
  "customer discounts delete": {
    value: "customer discounts delete",
    label: "delete",
    group: "customer discounts",
  },
  "customer discounts restore": {
    value: "customer discounts restore",
    label: "restore",
    group: "customer discounts",
  },
  "properties index": {
    value: "properties index",
    label: "index",
    group: "properties",
  },
  "properties create": {
    value: "properties create",
    label: "create",
    group: "properties",
  },
  "properties read": {
    value: "properties read",
    label: "read",
    group: "properties",
  },
  "properties update": {
    value: "properties update",
    label: "update",
    group: "properties",
  },
  "properties delete": {
    value: "properties delete",
    label: "delete",
    group: "properties",
  },
  "properties restore": {
    value: "properties restore",
    label: "restore",
    group: "properties",
  },
  "properties wizard": {
    value: "properties wizard",
    label: "wizard",
    group: "properties",
  },
  "subscriptions index": {
    value: "subscriptions index",
    label: "index",
    group: "subscriptions",
  },
  "subscriptions create": {
    value: "subscriptions create",
    label: "create",
    group: "subscriptions",
  },
  "subscriptions read": {
    value: "subscriptions read",
    label: "read",
    group: "subscriptions",
  },
  "subscriptions update": {
    value: "subscriptions update",
    label: "update",
    group: "subscriptions",
  },
  "subscriptions pause": {
    value: "subscriptions pause",
    label: "pause",
    group: "subscriptions",
  },
  "subscriptions continue": {
    value: "subscriptions continue",
    label: "continue",
    group: "subscriptions",
  },
  "subscriptions delete": {
    value: "subscriptions delete",
    label: "delete",
    group: "subscriptions",
  },
  "subscriptions restore": {
    value: "subscriptions restore",
    label: "restore",
    group: "subscriptions",
  },
  "subscriptions wizard": {
    value: "subscriptions wizard",
    label: "wizard",
    group: "subscriptions",
  },
  "subscription tasks index": {
    value: "subscription tasks index",
    label: "task index",
    group: "subscriptions",
  },
  "subscription schedules index": {
    value: "subscription schedules index",
    label: "schedule index",
    group: "subscriptions",
  },
  "subscription tasks create": {
    value: "subscription tasks create",
    label: "create task",
    group: "subscriptions",
  },
  "subscription tasks update": {
    value: "subscription tasks update",
    label: "update task",
    group: "subscriptions",
  },
  "subscription tasks delete": {
    value: "subscription tasks delete",
    label: "delete task",
    group: "subscriptions",
  },
  "companies index": {
    value: "companies index",
    label: "index",
    group: "companies",
  },
  "companies create": {
    value: "companies create",
    label: "create",
    group: "companies",
  },
  "companies read": {
    value: "companies read",
    label: "read",
    group: "companies",
  },
  "companies update": {
    value: "companies update",
    label: "update",
    group: "companies",
  },
  "companies delete": {
    value: "companies delete",
    label: "delete",
    group: "companies",
  },
  "companies restore": {
    value: "companies restore",
    label: "restore",
    group: "companies",
  },
  "companies wizard": {
    value: "companies wizard",
    label: "wizard",
    group: "companies",
  },
  "companies primary address read": {
    value: "companies primary address read",
    label: "read primary address",
    group: "companies",
  },
  "companies primary address update": {
    value: "companies primary address update",
    label: "update primary address",
    group: "companies",
  },
  "company invoice addresses index": {
    value: "company invoice addresses index",
    label: "invoice address index",
    group: "companies",
  },
  "company invoice addresses create": {
    value: "company invoice addresses create",
    label: "create invoice address",
    group: "companies",
  },
  "company invoice addresses update": {
    value: "company invoice addresses update",
    label: "update invoice address",
    group: "companies",
  },
  "company schedules index": {
    value: "company schedules index",
    label: "schedule index",
    group: "companies",
  },
  "company schedule histories index": {
    value: "company schedule histories index",
    label: "schedule history index",
    group: "companies",
  },
  "company credits index": {
    value: "company credits index",
    label: "credit index",
    group: "companies",
  },
  "company invoice addresses delete": {
    value: "company invoice addresses delete",
    label: "delete invoice address",
    group: "companies",
  },
  "company invoice addresses restore": {
    value: "company invoice addresses restore",
    label: "restore invoice address",
    group: "companies",
  },
  "company properties index": {
    value: "company properties index",
    label: "index",
    group: "company properties",
  },
  "company properties create": {
    value: "company properties create",
    label: "create",
    group: "company properties",
  },
  "company properties read": {
    value: "company properties read",
    label: "read",
    group: "company properties",
  },
  "company properties update": {
    value: "company properties update",
    label: "update",
    group: "company properties",
  },
  "company properties delete": {
    value: "company properties delete",
    label: "delete",
    group: "company properties",
  },
  "company properties restore": {
    value: "company properties restore",
    label: "restore",
    group: "company properties",
  },
  "company properties wizard": {
    value: "company properties wizard",
    label: "wizard",
    group: "company properties",
  },
  "company subscriptions index": {
    value: "company subscriptions index",
    label: "index",
    group: "company subscriptions",
  },
  "company subscriptions create": {
    value: "company subscriptions create",
    label: "create",
    group: "company subscriptions",
  },
  "company subscriptions read": {
    value: "company subscriptions read",
    label: "read",
    group: "company subscriptions",
  },
  "company subscriptions update": {
    value: "company subscriptions update",
    label: "update",
    group: "company subscriptions",
  },
  "company subscriptions pause": {
    value: "company subscriptions pause",
    label: "pause",
    group: "company subscriptions",
  },
  "company subscriptions continue": {
    value: "company subscriptions continue",
    label: "continue",
    group: "company subscriptions",
  },
  "company subscriptions delete": {
    value: "company subscriptions delete",
    label: "delete",
    group: "company subscriptions",
  },
  "company subscriptions restore": {
    value: "company subscriptions restore",
    label: "restore",
    group: "company subscriptions",
  },
  "company subscriptions wizard": {
    value: "company subscriptions wizard",
    label: "wizard",
    group: "company subscriptions",
  },
  "company subscription tasks index": {
    value: "company subscription tasks index",
    label: "task index",
    group: "company subscriptions",
  },
  "company subscription tasks create": {
    value: "company subscription tasks create",
    label: "create task",
    group: "company subscriptions",
  },
  "company subscription tasks update": {
    value: "company subscription tasks update",
    label: "update task",
    group: "company subscriptions",
  },
  "company subscription tasks delete": {
    value: "company subscription tasks delete",
    label: "delete task",
    group: "company subscriptions",
  },
  "company fixed prices index": {
    value: "company fixed prices index",
    label: "index",
    group: "company fixed prices",
  },
  "company fixed prices create": {
    value: "company fixed prices create",
    label: "create",
    group: "company fixed prices",
  },
  "company fixed prices read": {
    value: "company fixed prices read",
    label: "read",
    group: "company fixed prices",
  },
  "company fixed prices update": {
    value: "company fixed prices update",
    label: "update",
    group: "company fixed prices",
  },
  "company fixed prices delete": {
    value: "company fixed prices delete",
    label: "delete",
    group: "company fixed prices",
  },
  "company fixed prices restore": {
    value: "company fixed prices restore",
    label: "restore",
    group: "company fixed prices",
  },
  "company fixed price rows index": {
    value: "company fixed price rows index",
    label: "row index",
    group: "company fixed prices",
  },
  "company fixed price rows create": {
    value: "company fixed price rows create",
    label: "create row",
    group: "company fixed prices",
  },
  "company fixed price rows update": {
    value: "company fixed price rows update",
    label: "update row",
    group: "company fixed prices",
  },
  "company fixed price rows delete": {
    value: "company fixed price rows delete",
    label: "delete row",
    group: "company fixed prices",
  },
  "company discounts index": {
    value: "company discounts index",
    label: "index",
    group: "company discounts",
  },
  "company discounts create": {
    value: "company discounts create",
    label: "create",
    group: "company discounts",
  },
  "company discounts read": {
    value: "company discounts read",
    label: "read",
    group: "company discounts",
  },
  "company discounts update": {
    value: "company discounts update",
    label: "update",
    group: "company discounts",
  },
  "company discounts delete": {
    value: "company discounts delete",
    label: "delete",
    group: "company discounts",
  },
  "company discounts restore": {
    value: "company discounts restore",
    label: "restore",
    group: "company discounts",
  },
  "schedules index": {
    value: "schedules index",
    label: "index",
    group: "schedules",
  },
  "schedules read": {
    value: "schedules read",
    label: "read",
    group: "schedules",
  },
  "schedules update": {
    value: "schedules update",
    label: "update",
    group: "schedules",
  },
  "schedules cancel": {
    value: "schedules cancel",
    label: "cancel",
    group: "schedules",
  },
  "schedules reschedule": {
    value: "schedules reschedule",
    label: "reschedule",
    group: "schedules",
  },
  "schedule workers index": {
    value: "schedule workers index",
    label: "worker index",
    group: "schedules",
  },
  "schedule workers read": {
    value: "schedule workers read",
    label: "read worker",
    group: "schedules",
  },
  "schedule workers create": {
    value: "schedule workers create",
    label: "create worker",
    group: "schedules",
  },
  "schedule workers enable": {
    value: "schedule workers enable",
    label: "enable worker",
    group: "schedules",
  },
  "schedule workers disable": {
    value: "schedule workers disable",
    label: "disable worker",
    group: "schedules",
  },
  "schedule workers update attendance": {
    value: "schedule workers update attendance",
    label: "update attendance",
    group: "schedules",
  },
  "schedule tasks index": {
    value: "schedule tasks index",
    label: "task index",
    group: "schedules",
  },
  "schedule tasks create": {
    value: "schedule tasks create",
    label: "create task",
    group: "schedules",
  },
  "schedule tasks update": {
    value: "schedule tasks update",
    label: "update task",
    group: "schedules",
  },
  "schedule tasks delete": {
    value: "schedule tasks delete",
    label: "delete task",
    group: "schedules",
  },
  "schedule change requests index": {
    value: "schedule change requests index",
    label: "change request index",
    group: "schedules",
  },
  "schedule change requests create": {
    value: "schedule change requests create",
    label: "create change request",
    group: "schedules",
  },
  "schedule change requests approve": {
    value: "schedule change requests approve",
    label: "approve change request",
    group: "schedules",
  },
  "schedule change requests reject": {
    value: "schedule change requests reject",
    label: "reject change request",
    group: "schedules",
  },
  "orders index": {
    value: "orders index",
    label: "index",
    group: "orders",
  },
  "orders read": {
    value: "orders read",
    label: "read",
    group: "orders",
  },
  "order rows index": {
    value: "order rows index",
    label: "row index",
    group: "orders",
  },
  "order rows create": {
    value: "order rows create",
    label: "create row",
    group: "orders",
  },
  "order rows update": {
    value: "order rows update",
    label: "update row",
    group: "orders",
  },
  "order rows delete": {
    value: "order rows delete",
    label: "delete row",
    group: "orders",
  },
  "invoices index": {
    value: "invoices index",
    label: "index",
    group: "invoices",
  },
  "invoices read": {
    value: "invoices read",
    label: "read",
    group: "invoices",
  },
  "invoices create fortnox": {
    value: "invoices create fortnox",
    label: "create fortnox",
    group: "invoices",
  },
  "invoices send": {
    value: "invoices send",
    label: "send",
    group: "invoices",
  },
  "invoices update": {
    value: "invoices update",
    label: "update",
    group: "invoices",
  },
  "invoices cancel": {
    value: "invoices cancel",
    label: "cancel",
    group: "invoices",
  },
  "employees index": {
    value: "employees index",
    label: "index",
    group: "employees",
  },
  "employees create": {
    value: "employees create",
    label: "create",
    group: "employees",
  },
  "employees read": {
    value: "employees read",
    label: "read",
    group: "employees",
  },
  "employees update": {
    value: "employees update",
    label: "update",
    group: "employees",
  },
  "employees delete": {
    value: "employees delete",
    label: "delete",
    group: "employees",
  },
  "employees restore": {
    value: "employees restore",
    label: "restore",
    group: "employees",
  },
  "employee roles update": {
    value: "employee roles update",
    label: "update role",
    group: "employees",
  },
  "employee roles appoint superadmin": {
    value: "employee roles appoint superadmin",
    label: "appoint superadmin",
    group: "employees",
  },
  "employees wizard": {
    value: "employees wizard",
    label: "wizard",
    group: "employees",
  },
  "teams index": {
    value: "teams index",
    label: "index",
    group: "teams",
  },
  "teams create": {
    value: "teams create",
    label: "create",
    group: "teams",
  },
  "teams read": {
    value: "teams read",
    label: "read",
    group: "teams",
  },
  "teams update": {
    value: "teams update",
    label: "update",
    group: "teams",
  },
  "teams delete": {
    value: "teams delete",
    label: "delete",
    group: "teams",
  },
  "teams restore": {
    value: "teams restore",
    label: "restore",
    group: "teams",
  },
  "deviations index": {
    value: "deviations index",
    label: "index",
    group: "deviations",
  },
  "deviations create": {
    value: "deviations create",
    label: "create",
    group: "deviations",
  },
  "deviations read": {
    value: "deviations read",
    label: "read",
    group: "deviations",
  },
  "deviations handle": {
    value: "deviations handle",
    label: "handle",
    group: "deviations",
  },
  "time reports index": {
    value: "time reports index",
    label: "index",
    group: "time reports",
  },
  "services index": {
    value: "services index",
    label: "index",
    group: "services",
  },
  "services create": {
    value: "services create",
    label: "create",
    group: "services",
  },
  "services read": {
    value: "services read",
    label: "read",
    group: "services",
  },
  "services update": {
    value: "services update",
    label: "update",
    group: "services",
  },
  "services delete": {
    value: "services delete",
    label: "delete",
    group: "services",
  },
  "services restore": {
    value: "services restore",
    label: "restore",
    group: "services",
  },
  "service tasks index": {
    value: "service tasks index",
    label: "task index",
    group: "services",
  },
  "service tasks create": {
    value: "service tasks create",
    label: "create task",
    group: "services",
  },
  "service tasks update": {
    value: "service tasks update",
    label: "update task",
    group: "services",
  },
  "service tasks delete": {
    value: "service tasks delete",
    label: "delete task",
    group: "services",
  },
  "service translations update": {
    value: "service translations update",
    label: "update translations",
    group: "services",
  },
  "service quarters index": {
    value: "service quarters index",
    label: "index",
    group: "service quarters",
  },
  "service quarters create": {
    value: "service quarters create",
    label: "create",
    group: "service quarters",
  },
  "service quarters read": {
    value: "service quarters read",
    label: "read",
    group: "service quarters",
  },
  "service quarters update": {
    value: "service quarters update",
    label: "update",
    group: "service quarters",
  },
  "service quarters delete": {
    value: "service quarters delete",
    label: "delete",
    group: "service quarters",
  },
  "addons index": {
    value: "addons index",
    label: "index",
    group: "addons",
  },
  "addons create": {
    value: "addons create",
    label: "create",
    group: "addons",
  },
  "addons read": {
    value: "addons read",
    label: "read",
    group: "addons",
  },
  "addons update": {
    value: "addons update",
    label: "update",
    group: "addons",
  },
  "addons delete": {
    value: "addons delete",
    label: "delete",
    group: "addons",
  },
  "addons restore": {
    value: "addons restore",
    label: "restore",
    group: "addons",
  },
  "addon tasks index": {
    value: "addon tasks index",
    label: "task index",
    group: "addons",
  },
  "addon tasks create": {
    value: "addon tasks create",
    label: "create task",
    group: "addons",
  },
  "addon tasks update": {
    value: "addon tasks update",
    label: "update task",
    group: "addons",
  },
  "addon tasks delete": {
    value: "addon tasks delete",
    label: "delete task",
    group: "addons",
  },
  "addon translations update": {
    value: "addon translations update",
    label: "update translations",
    group: "addons",
  },
  "products index": {
    value: "products index",
    label: "index",
    group: "products",
  },
  "products create": {
    value: "products create",
    label: "create",
    group: "products",
  },
  "products read": {
    value: "products read",
    label: "read",
    group: "products",
  },
  "products update": {
    value: "products update",
    label: "update",
    group: "products",
  },
  "products delete": {
    value: "products delete",
    label: "delete",
    group: "products",
  },
  "products restore": {
    value: "products restore",
    label: "restore",
    group: "products",
  },
  "product translations update": {
    value: "product translations update",
    label: "update translations",
    group: "products",
  },
  "price adjustment index": {
    value: "price adjustment index",
    label: "index",
    group: "price adjustments",
  },
  "price adjustment create": {
    value: "price adjustment create",
    label: "create",
    group: "price adjustments",
  },
  "price adjustment update": {
    value: "price adjustment update",
    label: "update",
    group: "price adjustments",
  },
  "price adjustment delete": {
    value: "price adjustment delete",
    label: "delete",
    group: "price adjustments",
  },
  "price adjustment read": {
    value: "price adjustment read",
    label: "read",
    group: "price adjustments",
  },
  "blockdays index": {
    value: "blockdays index",
    label: "index",
    group: "blockdays",
  },
  "blockdays create": {
    value: "blockdays create",
    label: "create",
    group: "blockdays",
  },
  "blockdays update": {
    value: "blockdays update",
    label: "update",
    group: "blockdays",
  },
  "blockdays delete": {
    value: "blockdays delete",
    label: "delete",
    group: "blockdays",
  },
  "roles index": {
    value: "roles index",
    label: "index",
    group: "roles",
  },
  "roles create": {
    value: "roles create",
    label: "create",
    group: "roles",
  },
  "roles update": {
    value: "roles update",
    label: "update",
    group: "roles",
  },
  "roles delete": {
    value: "roles delete",
    label: "delete",
    group: "roles",
  },
  "system settings index": {
    value: "system settings index",
    label: "index",
    group: "system settings",
  },
  "system settings update": {
    value: "system settings update",
    label: "update",
    group: "system settings",
  },
  "key places index": {
    value: "key places index",
    label: "index",
    group: "key places",
  },
  "feedbacks index": {
    value: "feedbacks index",
    label: "index",
    group: "feedbacks",
  },
  "feedbacks create": {
    value: "feedbacks create",
    label: "create",
    group: "feedbacks",
  },
  "feedbacks delete": {
    value: "feedbacks delete",
    label: "delete",
    group: "feedbacks",
  },
  "feedbacks restore": {
    value: "feedbacks restore",
    label: "restore",
    group: "feedbacks",
  },
  "activity logs index": {
    value: "activity logs index",
    label: "index",
    group: "activity logs",
  },
  "activity logs delete": {
    value: "activity logs delete",
    label: "delete",
    group: "activity logs",
  },
  "authentication logs index": {
    value: "authentication logs index",
    label: "index",
    group: "authentication logs",
  },
  "authentication logs delete": {
    value: "authentication logs delete",
    label: "delete",
    group: "authentication logs",
  },
  "credits index": {
    value: "credits index",
    label: "index",
    group: "credits",
  },
  "notifications index": {
    value: "notifications index",
    label: "index",
    group: "notifications",
  },
  "notifications read": {
    value: "notifications read",
    label: "read",
    group: "notifications",
  },
  "notifications send": {
    value: "notifications send",
    label: "send",
    group: "notifications",
  },
  "credits create": {
    value: "credits create",
    label: "create",
    group: "credits",
  },
  "credits update": {
    value: "credits update",
    label: "update",
    group: "credits",
  },
  "credits delete": {
    value: "credits delete",
    label: "delete",
    group: "credits",
  },
  "schedules history create": {
    value: "schedules history create",
    label: "create history",
    group: "schedules",
  },
  "customer rut co applicant index": {
    value: "customer rut co applicant index",
    label: "rut co applicant index",
    group: "customers",
  },
  "customer rut co applicant create": {
    value: "customer rut co applicant create",
    label: "create rut co applicant",
    group: "customers",
  },
  "customer rut co applicant enable": {
    value: "customer rut co applicant enable",
    label: "enable rut co applicant",
    group: "customers",
  },
  "customer rut co applicant disable": {
    value: "customer rut co applicant disable",
    label: "disable rut co applicant",
    group: "customers",
  },
  "customer rut co applicant pause": {
    value: "customer rut co applicant pause",
    label: "pause rut co applicant",
    group: "customers",
  },
  "customer rut co applicant continue": {
    value: "customer rut co applicant continue",
    label: "continue rut co applicant",
    group: "customers",
  },
  "customer rut co applicant update": {
    value: "customer rut co applicant update",
    label: "update rut co applicant",
    group: "customers",
  },
  "customer rut co applicant delete": {
    value: "customer rut co applicant delete",
    label: "delete rut co applicant",
    group: "customers",
  },
  "unassign subscriptions index": {
    value: "unassign subscriptions index",
    label: "index",
    group: "unassign subscriptions",
  },
  "unassign subscriptions create": {
    value: "unassign subscriptions create",
    label: "create",
    group: "unassign subscriptions",
  },
  "unassign subscriptions update": {
    value: "unassign subscriptions update",
    label: "update",
    group: "unassign subscriptions",
  },
  "unassign subscriptions delete": {
    value: "unassign subscriptions delete",
    label: "delete",
    group: "unassign subscriptions",
  },
  "leave registrations index": {
    value: "leave registrations index",
    label: "index",
    group: "leave registrations",
  },
  "leave registrations create": {
    value: "leave registrations create",
    label: "create",
    group: "leave registrations",
  },
  "leave registrations update": {
    value: "leave registrations update",
    label: "update",
    group: "leave registrations",
  },
  "leave registrations delete": {
    value: "leave registrations delete",
    label: "delete",
    group: "leave registrations",
  },
  "leave registrations done": {
    value: "leave registrations done",
    label: "done",
    group: "leave registrations",
  },
  "time adjustments index": {
    value: "time adjustments index",
    label: "index",
    group: "time adjustments",
  },
  "time adjustments create": {
    value: "time adjustments create",
    label: "create",
    group: "time adjustments",
  },
  "time adjustments update": {
    value: "time adjustments update",
    label: "update",
    group: "time adjustments",
  },
  "time adjustments delete": {
    value: "time adjustments delete",
    label: "delete",
    group: "time adjustments",
  },
  "stores index": {
    value: "stores index",
    label: "index",
    group: "stores",
  },
  "stores read": {
    value: "stores read",
    label: "read",
    group: "stores",
  },
  "stores create": {
    value: "stores create",
    label: "create",
    group: "stores",
  },
  "stores update": {
    value: "stores update",
    label: "update",
    group: "stores",
  },
  "stores delete": {
    value: "stores delete",
    label: "delete",
    group: "stores",
  },
  "stores restore": {
    value: "stores restore",
    label: "restore",
    group: "stores",
  },
  "categories index": {
    value: "categories index",
    label: "index",
    group: "categories",
  },
  "categories create": {
    value: "categories create",
    label: "create",
    group: "categories",
  },
  "categories update": {
    value: "categories update",
    label: "update",
    group: "categories",
  },
  "categories delete": {
    value: "categories delete",
    label: "delete",
    group: "categories",
  },
  "categories restore": {
    value: "categories restore",
    label: "restore",
    group: "categories",
  },
  "categories translations update": {
    value: "categories translations update",
    label: "update translations",
    group: "categories",
  },
  "laundry orders index": {
    value: "laundry orders index",
    label: "index",
    group: "laundry orders",
  },
  "laundry orders create": {
    value: "laundry orders create",
    label: "create",
    group: "laundry orders",
  },
  "laundry orders update": {
    value: "laundry orders update",
    label: "update",
    group: "laundry orders",
  },
  "laundry orders delete": {
    value: "laundry orders delete",
    label: "delete",
    group: "laundry orders",
  },
  "laundry orders restore": {
    value: "laundry orders restore",
    label: "restore",
    group: "laundry orders",
  },
  "laundry orders read": {
    value: "laundry orders read",
    label: "read",
    group: "laundry orders",
  },
  "laundry order products create": {
    value: "laundry order products create",
    label: "create",
    group: "laundry order products",
  },
  "laundry order products update": {
    value: "laundry order products update",
    label: "update",
    group: "laundry order products",
  },
  "laundry order products delete": {
    value: "laundry order products delete",
    label: "delete",
    group: "laundry order products",
  },
  "laundry order products read": {
    value: "laundry order products read",
    label: "read",
    group: "laundry order products",
  },
  "laundry order schedules create": {
    value: "laundry order schedules create",
    label: "create",
    group: "laundry order schedules",
  },
  "laundry order schedules update": {
    value: "laundry order schedules update",
    label: "update",
    group: "laundry order schedules",
  },
  "laundry order schedules delete": {
    value: "laundry order schedules delete",
    label: "delete",
    group: "laundry order schedules",
  },
  "laundry order schedules read": {
    value: "laundry order schedules read",
    label: "read",
    group: "laundry order schedules",
  },
  "laundry order histories read": {
    value: "laundry order histories read",
    label: "read",
    group: "laundry order histories",
  },
} as const;

export default PERMISSIONS;
