trigger: none
pr: none

schedules:
  - cron: "0 0 * * *"
    displayName: Daily
    branches:
      include:
        - main
    always: "true"

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: Resources
      type: git
      name: DevOps-Utils

variables:
  - group: laravel-app

steps:
  - task: DownloadSecureFile@1
    name: mysqlRootCA
    inputs:
      secureFile: MySQLRootCA.crt.pem

  - bash: ls -l $(mysqlRootCA.secureFilePath)
    displayName: Check if certificate file exists

  - bash: |
      set -e
      echo "Backing up production database..."
      filename="$(date +%Y-%m-%d).sql"

      mysqldump --single-transaction \
        -h $PRODUCTION_DB_HOST \
        -u $PRODUCTION_DB_USER \
        -p$PRODUCTION_DB_PASSWORD \
        --ssl-ca=$CA_PATH \
        $PRODUCTION_DB_NAME > $filename

      echo "Backups complete."
      echo "##vso[task.setvariable variable=backupFilename]$filename"
    env:
      CA_PATH: $(mysqlRootCA.secureFilePath)
      PRODUCTION_DB_HOST: $(PRODUCTION_DB_HOST)
      PRODUCTION_DB_USER: $(PRODUCTION_DB_USER)
      PRODUCTION_DB_PASSWORD: $(PRODUCTION_DB_PASSWORD)
      PRODUCTION_DB_NAME: $(PRODUCTION_DB_NAME)
    displayName: Backup database

  - template: azure-pipelines/blob/upload.yaml@Resources
    parameters:
      azureSubscription: ARM-production-downstairs
      storageName: storageproddownstairs
      containerName: db-backups
      filePath: $(backupFilename)
      fileName: $(backupFilename)
